version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    ports:
      - "3306:3306"

  achat:
    image: yassinekh/devops:latest
    ports:
      - "8089:8089"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: achatdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    restart: on-failure
