version: '3.5'

services:
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    ports:
      - "3307:3306"

  backend:
    image: benjeddou_rafed_5arctic6-backend:latest
    container_name: backend
    ports:
      - "8089:8089"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/achatdb?createDatabaseIfNotExist=true&useUnicode=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    depends_on:
      - mysql
    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2

  front:
    container_name: frontend
    image: devops-project-front-front:latest
    volumes:
      - './:/usr/src/app'
    ports:
      - "8085:4200"
    command: >
      bash -c "npm start"
    depends_on:
      - backend

  nginx:
    container_name: nginx
    image: devops-project-front-nginx:latest
    ports:
      - "8082:80"
    command: ["nginx", "-g", "daemon off;"]

volumes:
  db:










