version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  spring-app:
    image: your-spring-boot-image
    container_name: spring-app-container
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/achatdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

  angular-app:
    build:
      context: khalilrez/angular-devops:1.0.0
      dockerfile: Dockerfile
    container_name: angular-app-container
    ports:
      - "4200:4200"
    depends_on:
      - spring-app
