version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"

  spring-app:
    image: khalilrez/achat:lts
    container_name: spring-app-container
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: mysql://mysql:3306/achatdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    restart: on-failure

  angular-app:
    image: khalilrez/devops-front:1.0.0
    container_name: angular-app-container
    ports:
      - "15000:80"
    depends_on:
      - spring-app
