version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    ports:
      - "3306:3306"
    networks:
      - net

  achat:
    image: yassinekh/devops:latest
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/achatdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - net

  front:
    image: yassinekh/front:latest
    ports:
      - "8085:80"
    depends_on:
      - achat
    restart: on-failure
    networks:
      - net
networks:
  net:
    driver: bridge