version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    ports:
      - "3306:3306"
    networks:
      - net

  achat:
    image: yassinekh/devops:latest
    ports:
      - "8089:8089"
    environment:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: achatdb
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - net
networks:
  net:
    driver: bridge