---
- name: Apply and wait for the mysql Kubernetes artifact
  hosts: all
  tasks:
    - name: Apply the mysql Kubernetes artifact
      command: minikube kubectl -- apply -f mysql-k8s.yml

    - name: Wait for the mysql artifact to be available
      shell: minikube kubectl -- wait --for=condition=available --timeout=300s -f mysql-k8s.yml
      register: wait_result
      ignore_errors: yes
      changed_when: wait_result.rc == 0

- name: Apply the second Kubernetes artifact
  tasks:
    - name: Apply the second Kubernetes artifact
      command: minikube kubectl -- apply -f spring-k8s.yml